### ISSUE TITLE
【Web动画】SVG 线条动画

### ISSUE THREAD

**Issue by chokcoco** [chokcoco/cnblogsArticle#13]
通常我们说的 Web 动画，包含了三大类。
+ `CSS3` 动画
+ `javascript` 动画（canvas）
+ `html` 动画（SVG）

个人认为 3 种动画各有优劣，实际应用中根据掌握情况作出取舍，本文讨论的是我认为 SVG 中在实际项目中非常有应用价值 SVG 线条动画。

## 举个栗子
SVG 线条动画，在一些特定的场合下可以解决使用 CSS 无法完成的动画。尤其是在进度条方面，看看最近项目里的一个小需求，一个这种形状的进度条：

![progressbar](https://cloud.githubusercontent.com/assets/8554143/21494108/2cab4188-cc4a-11e6-83c2-e9bd512a9aa9.jpg)

把里面的进度条单独拿出来，也就是需要实现这样一个效果：

![progress](https://cloud.githubusercontent.com/assets/8554143/21494256/0700ae68-cc4b-11e6-8dfb-338e7d0c7a72.gif)

脑洞大开一下，使用 CSS3 如何实现这样一个进度条呢。

CSS3 是可以做到的，就是很麻烦。但是如果采用 SVG 的话，迎刃而解。

<iframe height='265' scrolling='no' title='不规则进度条' src='//codepen.io/Chokcoco/embed/WogpWd/?height=265&theme-id=0&default-tab=css,result&embed-version=2' frameborder='no' allowtransparency='true' allowfullscreen='true' style='width: 100%;'>See the Pen <a href='https://codepen.io/Chokcoco/pen/WogpWd/'>不规则进度条</a> by Chokcoco (<a href='http://codepen.io/Chokcoco'>@Chokcoco</a>) on <a href='http://codepen.io'>CodePen</a>.
</iframe>

我们假定你在阅读本文的时候有了一定的 SVG 基础，上面代码看看就懂了，好了，本文到此结束。

![fuck](https://cloud.githubusercontent.com/assets/8554143/21494687/1e90d67c-cc4e-11e6-8406-c63a07f9be39.jpg)

好吧，还是稍微解释下，上面进度条的主要 SVG 代码如下：

```html
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xml:space="preserve" class="circle-load-rect-svg" width="300" height="200" viewbox="0 0 600 400">
    <polyline points="5 5, 575 5, 575 200, 5 200" fill="none" class="g-rect-path"/>
    <polyline points="5 5, 575 5, 575 200, 5 200" fill="none" class="g-rect-fill"/>
</svg>
```

## `SVG` 为何

可缩放矢量图形，即SVG，是W3C XML的分枝语言之一，用于标记可缩放的矢量图形。（摘自[MDN](https://developer.mozilla.org/zh-CN/docs/Web/SVG/Tutorial)）

上面代码中，先谈谈 `svg` 标签：

+ `version`： 表示 `<svg>` 的版本，目前只有 1.0，1.1 两种
+ `xmlns`：`http://www.w3.org/2000/svg` 固定值
+ `xmlns:xlink`：`http://www.w3.org/1999/xlink` 固定值
+ `xml:space`：`preserve` 固定值，上述三个值固定，表示命名空间，当数据单独存在`svg`文件内时，这3个值不能省略
+ `class`：就是我们熟悉的 class
+ `width` | `height`： 定义 `svg` 画布的大小
+ `viewbox`： 定义了画布上可以显示的区域，当 viewBox 的大小和 svg 不同时，viewBox 在屏幕上的显示会缩放至 svg 同等大小（暂时可以不用理解） 

有了 `svg` 标签，我们就可以愉快的在内部添加 `SVG` 图形了，上面，我在 `svg` 中定义了两个 `polyline ` 标签。

## `SVG` 基本形状

`polyline`：是SVG的一个基本形状，用来创建一系列直线连接多个点。

其实，`polyline` 是一个比较不常用的形状，比较常用的是`path`，`rect`，`circle` 等。这里我使用 `polyline` 的原因是需要使用 [`stroke-linejoin`](https://developer.mozilla.org/zh-CN/docs/Web/SVG/Attribute/stroke-linejoin) 和 [`stroke-linecap`](https://developer.mozilla.org/zh-CN/docs/Web/SVG/Attribute/stroke-linecap) 属性，在线段连接处创建圆滑过渡角。

SVG 中定义了一些[基本形状](https://developer.mozilla.org/zh-CN/docs/Web/SVG/Tutorial/Basic_Shapes)：

![shapes](https://cloud.githubusercontent.com/assets/8554143/21495623/aafea68e-cc53-11e6-8766-b87a76f80c56.png)

## `SVG` 线条动画

好，终于到本文的重点了。

![cry](https://cloud.githubusercontent.com/assets/8554143/21495794/b7085dca-cc54-11e6-9599-294bd6bfc710.jpg)

上面，我们给两个 `polyline` 都设置了 class，SVG 图形的一个好处就是部分属性样式可以使用 CSS 的方式书写，更重要的是可以配合 CSS 动画一起使用。

上面，主要的 CSS 代码：

```CSS
.g-rect-path{
    fill: none;
    stroke-width:10;
    stroke:#d3dce6;
    stroke-linejoin:round;
    stroke-linecap:round;
}

.g-rect-fill{
    fill: none;
    stroke-width:10;
    stroke:#ff7700;
    stroke-linejoin:round;
    stroke-linecap:round;
    stroke-dasharray: 0, 1370;
    stroke-dashoffset: 0;
    animation: lineMove 2s ease-out infinite;
}

@keyframes lineMove {
    0%{
        stroke-dasharray: 0, 1350;
    }
    100%{
        stroke-dasharray: 1350, 1350;
    }
}
```
